#!/usr/bin/env bash
#
# Installs Aero Messenger so it is launchable globally (a `aero-messenger`
# command on your PATH) and findable in your desktop application launcher.
#
# It is safe to re-run; it just overwrites the launcher + desktop entry.
set -euo pipefail

APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="$HOME/.local/bin"
DESKTOP_DIR="$HOME/.local/share/applications"
WRAPPER="$BIN_DIR/aero-messenger"
DESKTOP_FILE="$DESKTOP_DIR/aero-messenger.desktop"
ICON="$APP_DIR/assets/icon.svg"

mkdir -p "$BIN_DIR" "$DESKTOP_DIR"

# 1) Global launcher command (also used by the desktop entry).
cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# Auto-generated by install.sh — launches Aero Messenger from anywhere.
cd "$APP_DIR" || exit 1
exec node launch.js "\$@"
EOF
chmod +x "$WRAPPER"

# 2) Desktop entry for the application launcher.
cat > "$DESKTOP_FILE" <<EOF
[Desktop Entry]
Type=Application
Name=Aero Messenger
GenericName=WhatsApp Client
Comment=Frutiger Aero styled WhatsApp messenger
Exec=$WRAPPER
Icon=$ICON
Terminal=false
Categories=Network;InstantMessaging;Chat;
Keywords=whatsapp;chat;messenger;aero;
StartupNotify=true
StartupWMClass=Aero Messenger
EOF

# 3) Refresh the launcher's cache (best-effort).
if command -v update-desktop-database >/dev/null 2>&1; then
  update-desktop-database "$DESKTOP_DIR" >/dev/null 2>&1 || true
fi

echo "Installed:"
echo "  command : $WRAPPER  (run 'aero-messenger' from anywhere)"
echo "  launcher: $DESKTOP_FILE"
echo
case ":$PATH:" in
  *":$BIN_DIR:"*) : ;;
  *) echo "NOTE: $BIN_DIR is not on your PATH. Add this to ~/.bashrc:"
     echo "      export PATH=\"\$HOME/.local/bin:\$PATH\"" ;;
esac
echo "You can now find 'Aero Messenger' in your application launcher."
